add button
AlexanderGitSafronov/Note_app pull request #2
Opened 2023-04-10 10:48 UTC by AlexanderGitSafronov

2023-04-10 13:57 UTC, vadym-lohvynovych requested changes

2023-04-10 13:57 UTC, madvingovich commented on src/css/style.css
> +.add__task {
Чи тобі справді потрібні такі складні стилі на таку просту кнопку з плюсиком?

2023-04-10 14:06 UTC, AlexanderGitSafronov commented on src/css/style.css
> +.add__task {
Занадто абстрактно. Пока що я не бачу нічого складного в відносному позиуіонуванні і ширини і висоти всього екрана щоб розміщувати кнопку в низу кожного екрана.

2023-04-11 09:41 UTC, madvingovich approved these changes

2023-04-11 09:43 UTC, merged