save notes
AlexanderGitSafronov/Note_app pull request #7
Opened 2023-04-12 16:09 UTC by AlexanderGitSafronov

2023-04-14 06:32 UTC, madvingovich requested changes

2023-04-14 06:32 UTC, madvingovich commented on src/js/main.js
> +function noteHtml(id,title,subtitle) {
getNoteHTML підходить краще

2023-04-14 06:32 UTC, madvingovich commented on src/js/main.js
> +        return noteHtml(item.id,item.title,item.subtitle)
тут ретурн зайвий, можна в одну лінію

2023-04-15 07:34 UTC, madvingovich requested changes

2023-04-15 07:34 UTC, madvingovich commented on src/js/main.js
> +    localStorage.setItem("notes", JSON.stringify(localNotes));
Може краще це теж винести в handleNoteCreation?

2023-04-15 08:31 UTC, AlexanderGitSafronov commented on src/js/main.js
> +    localStorage.setItem("notes", JSON.stringify(localNotes));
Зробив

2023-04-15 16:31 UTC, AlexanderGitSafronov commented on src/js/main.js
> +    localStorage.setItem("notes", JSON.stringify(localNotes));
Може треба в функцію винести і там її визивати , я хз. Я чото не дуже орієнтуюсь де саме потрібна функція і куда краще вставити

2023-04-15 16:32 UTC, madvingovich approved these changes

2023-04-15 16:33 UTC, merged